name: sod

channels:
  - conda-forge

dependencies:
  - pip
  - python=3.7.6
  - setuptools
  - autopep8
  - pytest
  - ipykernel
  - pyyaml
  - scikit-image
  - nomkl
  - aiofiles
  - pip:
    - pandas
    - fastapi
    - uvicorn
    - pydantic
    - torch
    - torchvision
    - python-multipart
